### ISSUE TITLE
Pointers

### ISSUE THREAD

**Issue by adswa** [dbkeator/segstats_jsonld#24]
@satra or @dbkeator , could you point me to the PyNIDM search tool that queries scicrunch interactively?

**Comment by dbkeator** [comment]
@adswa It's the "map_vars_to_terms" function in  [Utils.py](https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/Utils.py#L560).

To see how I use it look at [CSV2NIDM](https://github.com/incf-nidash/PyNIDM/blob/master/nidm/experiment/tools/CSV2NIDM.py#L109)
