### ISSUE TITLE
having problem with hasLaterality converting lh.aparc.stats

### ISSUE THREAD

**Issue by dbkeator** [dbkeator/segstats_jsonld#5]
Here's the problem trace....not sure if this is related to InterLex scraping of anatomical CDEs or not...

Traceback (most recent call last):
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 2.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 575, in <module>
    main(sys.argv[1:])
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 559, in main
    add_seg_data(nidmdoc=nidmdoc,measure=measures,header=header, json_map=json_map)
  File "/Users/dbkeator/Documents/Coding/segstats_jsonld/segstats_jsonld/fs_to_nidm.py", line 135, in add_seg_data
    QualifiedName(provNamespace("hasLaterality","http://uri.interlex.org/ilx_0381387#"),""):json_map['Anatomy'][measures["structure"]]['hasLaterality'],
KeyError: 'hasLaterality'

**Comment by jgrethe** [comment]
There was a space in the default label.  So edited that to match and added the label with a space to synonyms.

**Comment by adswa** [comment]
Thx, can we close this then?

**Comment by jgrethe** [comment]
Don’t know if that fixed what Dave saw...

> On Jun 10, 2019, at 22:31, Adina Wagner <notifications@github.com> wrote:
> 
> Thx, can we close this then?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dbkeator_segstats-5Fjsonld_issues_5-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAMPEZNDZ2WY2EOO2XCFV3LPZ42DFA5CNFSM4HWUQYYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXL7O2Y-23issuecomment-2D500692843&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=c42GE_UFYynW6_vFHwVgVMtd1754jFQ36JGOJaf2T5g&s=U0FWftlVPTRnkVKaPj0ORD0PcVOGu_0ovrxbHKB0M4E&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAMPEZLHBGDAJMSHESVVT2LPZ42DFANCNFSM4HWUQYYA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=c42GE_UFYynW6_vFHwVgVMtd1754jFQ36JGOJaf2T5g&s=GkA2IgpJge70DDRqb8bC63Gkuia28o6TxcOUQcG26MY&e=>.
> 

_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644

UCSD Profile: http://profiles.ucsd.edu/jeffrey.grethe <http://profiles.ucsd.edu/jeffrey.grethe>
ORCID: http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
LinkedIn: http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by dbkeator** [comment]
Solved by checking whether anatomy CDE has a laterality designation...
