### ISSUE TITLE
There are no tests yet - lets write some

### ISSUE THREAD

**Issue by adswa** [dbkeator/segstats_jsonld#7]
As a general note, we should start writing unit tests and continuous integration.

**Comment by adswa** [comment]
Hey @dbkeator,

##############################################################################
only read this after your holiday! :-) Its not important, and if you forget, I'll remind you in July :-)
##############################################################################

In order to get continuous integration up and running, the repos admin (i.e. you) will have to enable CI. I propose Travis, but if you have other suggestions, I'm open to them.
If you could just [log in to travis](https://travis-ci.org/), and add this repository by searching for it within and clicking the little switch (should be here after log in: https://travis-ci.org/account/repositories), I can take care of all the rest.

**Comment by adswa** [comment]
(ping @dbkeator)

**Comment by dbkeator** [comment]
@adswa Done!
