### ISSUE TITLE
potential packages to add to requirements.txt

### ISSUE THREAD

**Issue by dbkeator** [dbkeator/segstats_jsonld#9]
https://github.com/RDFLib/rdflib-jsonld
-This only support JSON-LD ver. 1.0
https://github.com/satra/nidm-jsonld
-This supports JSON-LD ver. 1.1 with improved context support
-this repo is for saving JSON-LD with proper NIDM & DataLad style context
-Satra suggests save JSON-LD using rdflib-jsonld, then read in JSON-LD and re-save using nidm-jsonld.

**Comment by adswa** [comment]
I believe rdflib is part of `requirements.txt`, and `nidm-jsonld` doesn't seem to be a package and as such not installable. But I will add it as a .gitsubmodule
